spring.datasource.url=jdbc:postgresql://localhost:5432/Compito
spring.datasource.username=postgres
spring.datasource.password=matteo03
spring.datasource.driver-class-name=org.postgresql.Driver
server.error.include-message=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true